### PR TITLE
Added a test for a simple sql injection.

### PR DESCRIPTION
**Pull request by pstaabp**
This adds a test or a simple sql injection.  To use you will need to provide a course with a username/password to be able to login.

### CODE REVIEW

**Comment by mgage** [comment]
This is great Peter!  I’ll take a closer look at it later today.  — Mike

**Comment by pstaabp** [comment]
I've got a whole folder full of tests for Dancer2 and this just does a couple of little tests.  Obviously, we should test many of the other routines in instructorXMLHandler as well, but it's a start.

**Comment by pstaabp** [comment]
Looks like I can't switch to openwebwork here.  I will pull through another PR to openwebwork/develop and delete this one.

**Comment by mgage** [comment]
Hi Peter.  Why can't you merge this PR?  You can merge it from the website at https://github.com/mgage/webwork2/pull/18

**Comment by pstaabp** [comment]
I requested my script to be pulled into your `develop_sql_injection_bug` branch.  Then I can pull into openwebwork/develop.

**Pull request merged**
